### ISSUE TITLE
Version bumping in the git repo

### ISSUE THREAD

**Issue by ChocPanda** [ChocPanda/mambda#29]
**Describe the bug**
The main package.json version number isn't bumped in git

**To Reproduce**
Release

**Expected behavior**
package version correct in github

**Comment by ChocPanda** [comment]
Attempted to fix this with a post publish script but got the following error in the build

`'internal/modules/cjs/loader.js:628\n' +
    '    throw err;\n' +
    '    ^\n' +
    '\n' +
    "Error: Cannot find module '/home/circleci/project/dist/scripts/post-publish.js'\n" +
    '    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:625:15)\n' +
    '    at Function.Module._load (internal/modules/cjs/loader.js:527:27)\n' +
    '    at Function.Module.runMain (internal/modules/cjs/loader.js:839:10)\n' +
    '    at internal/main/run_main_module.js:17:11 {\n' +
    "  code: 'MODULE_NOT_FOUND',\n" +
    '  requireStack: []\n' +
    '}\n' +
    'npm ERR! code ELIFECYCLE\n' +
    'npm ERR! errno 1\n' +
    'npm ERR! mambda@2.1.0 postpublish: `node ./scripts/post-publish.js`\n' +
    'npm ERR! Exit status 1\n' +
    'npm ERR! \n' +
    'npm ERR! Failed at the mambda@2.1.0 postpublish script.\n' +
    'npm ERR! This is probably not a problem with npm. There is likely additional logging output above.\n' +
    '\n' +
    'npm ERR! A complete log of this run can be found in:\n' +
    'npm ERR!     /home/circleci/.npm/_logs/2019-07-07T13_45_54_491Z-debug.log\n',
`
